// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3ydmBleBmnmR4Nh0ue7LZdA1wffUJRpU',
    appId: '1:303415011687:web:4d5ec10ba9d24b902667c2',
    messagingSenderId: '303415011687',
    projectId: 'project-weedool-app-ios-aos',
    authDomain: 'project-weedool-app-ios-aos.firebaseapp.com',
    storageBucket: 'project-weedool-app-ios-aos.appspot.com',
    measurementId: 'G-GRW95YQFVZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBm7bzn2kkofVA0U5buzVHKixxVuYd-6Po',
    appId: '1:303415011687:android:73299fed9562241a2667c2',
    messagingSenderId: '303415011687',
    projectId: 'project-weedool-app-ios-aos',
    storageBucket: 'project-weedool-app-ios-aos.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgU2wqUnjUMEReH6p11FWzsASD3YPuSHQ',
    appId: '1:303415011687:ios:e4aaf9d73263cea02667c2',
    messagingSenderId: '303415011687',
    projectId: 'project-weedool-app-ios-aos',
    storageBucket: 'project-weedool-app-ios-aos.appspot.com',
    androidClientId: '303415011687-3b0rupik6v4na8lb853g0g81sghh1bdu.apps.googleusercontent.com',
    iosBundleId: 'com.turingbio.weedool.service.projectWeedoolTuring',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgU2wqUnjUMEReH6p11FWzsASD3YPuSHQ',
    appId: '1:303415011687:ios:8065716fa95e8e942667c2',
    messagingSenderId: '303415011687',
    projectId: 'project-weedool-app-ios-aos',
    storageBucket: 'project-weedool-app-ios-aos.appspot.com',
    androidClientId: '303415011687-3b0rupik6v4na8lb853g0g81sghh1bdu.apps.googleusercontent.com',
    iosBundleId: 'com.example.weedool.RunnerTests',
  );
}
